# Generated by Django 4.2.7 on 2023-11-30 23:36

import TeknoBlog.custom_storages
import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="iletisimmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                (
                    "icerik",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        null=True,
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name_plural": "iletişim Formu",},
        ),
        migrations.CreateModel(
            name="PostKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("H1", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        null=True,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("short_title", models.CharField(blank=True, max_length=255)),
                ("Aktif", models.BooleanField(default=False)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Post Kategori",},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Masal Hiyenin başlığını girin.", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Şiirin URL'de görünecek kısmını girin.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "h1",
                    models.CharField(
                        blank=True,
                        help_text="İçeriğin H1 Seo uyumlu girilmesi Lazım.",
                        max_length=255,
                    ),
                ),
                (
                    "icerik",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Şiirin içeriğini girin.", null=True
                    ),
                ),
                (
                    "resim",
                    models.ImageField(
                        blank=True,
                        help_text="858 x 400",
                        null=True,
                        storage=TeknoBlog.custom_storages.ImageSettingStorage(),
                        upload_to=blog.models.kapak_resmi_upload_to,
                    ),
                ),
                ("youtube", models.URLField(blank=True)),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        verbose_name="Meta Açıklama",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        verbose_name="Anahtar Kelimeler",
                    ),
                ),
                (
                    "yayin_tarihi",
                    models.DateTimeField(
                        blank=True,
                        help_text="Postanın yayınlanacağı tarih ve saat",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Taslak", "Taslak"),
                            ("Hazir", "Hazir"),
                            ("Yayinda", "Yayinda"),
                            ("oto", "oto"),
                            ("manuel", "manuel"),
                        ],
                        default="Taslak",
                        help_text="Şiirin durumunu seçin.",
                        max_length=10,
                    ),
                ),
                (
                    "aktif",
                    models.BooleanField(
                        default=False,
                        help_text="Şiirin aktif olup olmadığını belirtin.",
                    ),
                ),
                (
                    "banner",
                    models.BooleanField(
                        default=False,
                        help_text="Ana Sayfadaki büyük resim alanında ögrünür",
                    ),
                ),
                (
                    "small_banner",
                    models.BooleanField(
                        default=False, help_text="Ana sayfada küçük resimlerde görünür."
                    ),
                ),
                ("okunma_sayisi", models.PositiveBigIntegerField(default=0)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "Post_Turu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.postkategori",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Post",},
        ),
    ]
