# Generated by Django 4.2.7 on 2023-12-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="yazar",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Melih ÖZKAŞ", "Melih ÖZKAŞ"),
                    ("Hava ÖZKAŞ", "Hava ÖZKAŞ"),
                    ("Ayşe POLAT", "Ayşe POLAT"),
                    ("Fatma ÖZTÜRK", "Fatma ÖZTÜRK"),
                    ("Ebru GÜNEŞ", "Ebru GÜNEŞ"),
                    ("Adem YALÇIN", "Adem YALÇIN"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
