# Generated by Django 4.2.7 on 2023-12-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_resim_post_image"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="image", new_name="resim",),
    ]
