# Generated by Django 4.2.7 on 2023-12-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_small_banner_post_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Kaynak_Linki",
            field=models.URLField(blank=True, null=True),
        ),
    ]
