# Generated by Django 4.2.7 on 2023-12-06 21:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_kaynak_linki"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kontrol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Masal Hiyenin başlığını girin.", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        help_text="Masal Hiyenin başlığını girin.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "h1",
                    models.CharField(
                        blank=True,
                        help_text="İçeriğin H1 Seo uyumlu girilmesi Lazım.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "icerik",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Şiirin içeriğini girin.", null=True
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Sayfanın meta açıklamasını girin.",
                        verbose_name="Meta Açıklama",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Sayfanın anahtar kelimelerini \" Virgül '  ' \" ile ayrınız. ",
                        max_length=255,
                        verbose_name="Anahtar Kelimeler",
                    ),
                ),
                (
                    "Akibeti",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Salla", "Salla"),
                            ("Tamamlandi", "Tamamlandi"),
                            ("Hazirla", "Hazirla"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("Kaynak_Linki", models.URLField(blank=True, null=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "Post_Turu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blog.postkategori",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Kontrol",},
        ),
    ]
